name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: nuget/setup-nuget@v1.0.5
    - name: Add Monitoring Solutions SECRET
      run: |
        nuget source Add -Name "MonSol" -Source "https://nuget.pkg.github.com/MonitoringSolutionsInc/index.json" -Username ${{ secrets.ORGANIZATION_REPO_ACCESS_USERNAME }} -Password ${{ secrets.ORGANIZATION_REPO_ACCESS }}
        nuget setApiKey ${{ secrets.ORGANIZATION_REPO_ACCESS }} -Source "https://nuget.pkg.github.com/MonitoringSolutionsInc/index.json"
    - name: Restore dependencies
      run: nuget restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
